# Generated by Django 5.2.1 on 2025-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_weight",
            field=models.CharField(
                blank=True, help_text="Selected weight (e.g., 500g, 1kg)", max_length=20
            ),
        ),
    ]
