# Generated by Django 5.2.1 on 2025-06-08 09:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.AddField(
            model_name="product",
            name="available_weights",
            field=models.JSONField(
                default=list,
                help_text="List of available weights for this product. Example: ['250g', '500g', '1kg']",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price for base weight (500g)",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_seasonal",
            field=models.BooleanField(default=False),
        ),
    ]
